spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mall-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: amos.wang:8088
    sentinel:
      filter:
        enabled: false
      transport:
        port: 8001
        dashboard: localhost:8002
      datasource:
        ds:
          nacos:
            server-addr: amos.wang:8088
            data-id: ${spring.application.name}-sentinel
            group-id: DEFAULT_GROUP
            rule-type: flow
            # data-type: json [default: json]
    gateway:
      routes:
        # mall-order
        - id: route_order
          uri: lb://mall-order/order/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: route_order_swagger
          uri: lb://mall-order/
          predicates:
            - Path=/mall-order/**
          filters:
            - StripPrefix=1

        # mall-user
        - id: route_user
          uri: lb://mall-user/user/
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: route_user_swagger
          uri: lb://mall-user/
          predicates:
            - Path=/mall-user/**
          filters:
            - StripPrefix=1
    stream:
      kafka:
        binder:
          brokers: 172.16.35.22:9092
        bindings: 
          hello-in:
            destination: hello
            content-type: application/json
          hello-out:
            destination: hello
            content-type: application/json

  redis:
    host: amos.wang
    database: 1
    port: 1998

server:
  port: 8000

info:
  app:
    name: ${spring.application.name}
    description: 网关系统
    version: 1.0.0

feign:
  sentinel:
    enabled: true