spring:
  main:
    # 后定义的bean会覆盖之前定义的相同名称的bean
    allow-bean-definition-overriding: true
  application:
    name: mall-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: amos.wang:8088
    gateway:
      routes:
        - id: route_order
          uri: lb://mall-order/order/
          predicates:
            - Path=/order/**

        - id: route_user
          uri: lb://mall-user/user/
          predicates:
            - Path=/user/**
  redis:
    host: amos.wang
    database: 1
    port: 1998

server:
  port: 8000

info:
  app:
    name: ${spring.application.name}
    description: 网关系统
    version: 1.0.0

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000
  # 负载均衡策略 com.netflix.loadbalancer.BestAvailableRule
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#配置请求超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

#turbine:
#  cluster-name-expression: "default"
#  app-config-list: []
