spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mall-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: amos.wang:8088
    sentinel:
      transport:
        port: 8001
        dashboard: localhost:8002
    gateway:
      routes:
        - id: route_order
          uri: lb://mall-order/order/
          predicates:
            - Path=/order/**

        - id: route_user
          uri: lb://mall-user/user/
          predicates:
            - Path=/user/**
  redis:
    host: amos.wang
    database: 1
    port: 1998

server:
  port: 8000

info:
  app:
    name: ${spring.application.name}
    description: 网关系统
    version: 1.0.0

feign:
  sentinel:
    enabled: true