# 基础配置
spring:
  application:
    name: mall-user
  cloud:
    nacos:
      discovery:
        server-addr: amos.wang:8088
server:
  port: 8010

info:
  app:
    name: ${spring.application.name}
    description: 用户系统
    version: 1.0.0


# eureka 服务注册中心配置
