# 基础配置
spring:
  application:
    name: mall-user
server:
  port: 8010

info:
  app:
    name: ${spring.application.name}
    description: 用户系统
    version: 1.0.0


# eureka 服务注册中心配置
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
