# 基础配置
spring:
  application:
    name: mall-warehouse
  cloud:
    nacos:
      discovery:
        server-addr: amos.wang:8088
server:
  port: 8030

info:
  app:
    name: ${spring.application.name}
    description: 仓储系统
    version: 1.0.0
