server:
  port: 8030

redisson:
  singleServerConfig:
    address: 127.0.0.1:6379

spring:
  cloud:
    stream:
      bindings:
        order:
          group: warehouseProcess
          destination: order_create
          content-type: application/json
