version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3.8.7-management-alpine
    restart: always
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin