spring:
  application:
    name: mall-server

eureka:
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka,http://slave2:8762/eureka,http://slave3:8763/eureka

info:
  app:
    name: mall-server
    description: Eureka 注册中心
    version: 1.0.0

---
spring:
  profiles:
    slave1
server:
  port: 8761
eureka:
  instance:
    hostname: slave1

---
spring:
  profiles:
    slave2
server:
  port: 8762
eureka:
  instance:
    hostname: slave2

---
spring:
  profiles:
    slave3
server:
  port: 8763
eureka:
  instance:
    hostname: slave3