spring:
  application:
    name: mall-server
eureka:
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka,http://slave2:8762/eureka

---
# 主机名
spring:
  profiles:
    slave1
server:
  port: 8761
eureka:
  instance:
    hostname: slave1

---
# 主机名
spring:
  profiles:
    slave2
server:
  port: 8762
eureka:
  instance:
    hostname: slave2