# 基础配置
spring:
  application:
    name: mall-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: host_route_order
#          uri: http://mall-order/order/
#          predicates:
#            - Path=/order/**
#
#        - id: host_route_user
#          uri: http://localhost:8091/user/
#          predicates:
#            - Path=/user/**

server:
  port: 8090

info:
  app:
    name: ${spring.application.name}
    description: 网关系统
    version: 1.0.0

# eureka 服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
