# 基础配置

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mall-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: host_route_order
#          uri: http://mall-order/order/
#          predicates:
#            - Path=/order/**
#
#        - id: host_route_user
#          uri: http://localhost:8091/user/
#          predicates:
#            - Path=/user/**

server:
  port: 8000

info:
  app:
    name: ${spring.application.name}
    description: 网关系统
    version: 1.0.0

# eureka 服务注册中心配置
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

ribbon:
  #  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#turbine:
#  cluster-name-expression: "default"
#  app-config-list: []

# log config
logging:
  level:
    springfox:
      documentation: WARN

# show swagger-ui
swagger:
  enable: true