-- 创建数据库
CREATE DATABASE mall CHARACTER
SET = 'utf8' COLLATE = 'utf8_general_ci';

-- ----------------------------
-- Table structure for order
-- ----------------------------
DROP TABLE
IF EXISTS `apply_order`;

CREATE TABLE `apply_order` (
  `ID` BIGINT (11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `USER_ID` BIGINT (11) NOT NULL COMMENT '用户ID',
  `ORDER_NO` VARCHAR (64) NOT NULL COMMENT '订单编号',
  `CONSUME_DATE` date DEFAULT NULL COMMENT '消费日期',
  `CONSUME_TIME` datetime DEFAULT NULL COMMENT '消费时间',
  `CONSUME_AMOUNT` DECIMAL (8, 2) DEFAULT NULL COMMENT '消费金额',
  `REDUCE_AMOUNT` DECIMAL (8, 2) DEFAULT NULL COMMENT '优惠金额',
  `REDUCE_REASON` VARCHAR (255) DEFAULT NULL COMMENT '优惠原因',
  `SERIAL_NO` VARCHAR (64) DEFAULT NULL COMMENT '交易流水号',
  `ORDER_STATUS` VARCHAR (64) DEFAULT NULL COMMENT '订单状态',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_general_ci COMMENT = '订单表';

-- ----------------------------
-- Table structure for order_detail
-- ----------------------------
DROP TABLE
IF EXISTS `order_detail`;

CREATE TABLE `order_detail` (
  `ID` BIGINT (11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `ORDER_NO` VARCHAR (64) NOT NULL COMMENT '订单编号',
  `PRODUCT_NAME` VARCHAR (128) DEFAULT NULL COMMENT '消费商品名称',
  `PRODUCT_UNIT_PRICE` DECIMAL (8, 2) DEFAULT NULL COMMENT '消费商品单价',
  `PRODUCT_COUNT` INT (11) DEFAULT NULL COMMENT '消费商品数量',
  `CONSUME_TIME` datetime DEFAULT NULL COMMENT '消费时间',
  `ADDRESS` VARCHAR (255) DEFAULT NULL COMMENT '地址',
  `CREATE_TIME` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_general_ci COMMENT = '订单详情表';

-- -----