server:
  port: 8010

spring:
  cloud:
    stream:
      kafka:
        bindings:
          hello_chan:
            destination: hello
            content-type: application/json
          order:
            destination: order_create
            content-type: application/json
