spring:
  application:
    name: mall-user
  cloud:
    nacos:
      discovery:
        server-addr: amos.wang:8088

server:
  port: 8010

info:
  app:
    name: ${spring.application.name}
    description: 用户系统
    version: 1.0.0

# set swagger logger level
logging:
  level:
    springfox:
      documentation: WARN

# set enable status
swagger:
  enable: true