spring:
  application:
    name: mall-user
  cloud:
    nacos:
      discovery:
        server-addr: amos.wang:8088
    stream:
      kafka:
        binder:
          brokers: 172.16.23.35:9092
        bindings:
          hello-in:
            destination: hello
            content-type: application/json
          hello-out:
            destination: hello
            content-type: application/json

server:
  port: 8010

info:
  app:
    name: ${spring.application.name}
    description: 用户系统
    version: 1.0.0

# set swagger logger level
logging:
  level:
    springfox:
      documentation: WARN

# set enable status
swagger:
  enable: true