server:
  port: 8010

spring:
  cloud:
    stream:
      bindings:
        hello_chan:
          destination: hello
          content-type: application/json
        order:
          group: userProcess
          destination: order_create
          content-type: application/json
